---
- hosts: jenkins-master
  become: yes
  tasks:
  - name: installing java
    apt:
        name: openjdk-11-jre
        state: present
  - name: adding jenkins key
    ansible.builtin.apt_key:
        url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
  - name: adding jenkins repo
    apt_repository:
        repo: 'deb  https://pkg.jenkins.io/debian-stable binary/'
        state: present
  - name: installing jenkins
    apt:
       name: jenkins
       state: present
  - name: start the jenkins service
    service:
       name: jenkins
       state: started
  - name: Enable jenkins during boot
    service:
       name: jenkins
       enabled: yes
  - name: inistial adimin password
    command:
       cmd: 'cat /var/lib/jenkins/secrets/initialAdminPassword'
    register: initial_admin_password
  - name: Display the content of initial admin password
    debug:
       var: initial_admin_password.stdout_lines